### ISSUE TITLE
[FR] Update the sample to demonstrate use-case of showing dialog using custom `RequestStrategy`

### ISSUE THREAD

**Issue by KaustubhPatange** [LikeTheSalad/aaper#4]
Since this is the most common use-case where the app shows a dialog explaining why they need permissions before requesting, it might be difficult for some users to figure out the solution independently, especially if they are a beginner.

No doubt your documentation is excellent but an example would be great to show this use-case.

As I was experimenting with this library I updated the sample (locally) to demonstrate this use-case & would be happy to send a PR if you agree to this?

**Comment by LikeTheSalad** [comment]
Hi!

Many thanks for your feedback on it and thanks for taking the time! I'm always open to get any type of suggestions to improve any aspect of my projects so please, by all means, raise a PR with your changes and I'll gladly take a look at it! 👍 

Regards,
Cesar
